// ABOUTME: Examples section - thesis preview with visual card design
// ABOUTME: Shows real thesis download with stats and preview

import { Button } from "@/components/ui/button";
import { Download, FileText, BookOpen, Quote, Clock, Code } from "lucide-react";
import Link from "next/link";

const stats = [
  { icon: FileText, value: "104", label: "Pages" },
  { icon: BookOpen, value: "30k+", label: "Words" },
  { icon: Quote, value: "200+", label: "Citations" },
  { icon: Clock, value: "~20", label: "Minutes" },
];

export const ExamplesSection = () => {
  return (
    <section id="examples" className="py-24 sm:py-32 border-t border-border/50">
      <div className="container">
        <div className="max-w-2xl mx-auto text-center mb-12">
          <p className="text-sm font-medium text-accent mb-3">Real Example</p>
          <h2 className="text-3xl md:text-4xl font-semibold tracking-tight mb-4">
            See what AI can generate
          </h2>
          <p className="text-muted-foreground">
            Download a complete master&apos;s thesis generated by OpenDraft in under 20 minutes.
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          {/* Thesis Preview Card */}
          <div className="bg-card border border-border rounded-2xl overflow-hidden">
            {/* Header with thesis title */}
            <div className="bg-accent/5 border-b border-border p-6">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-16 h-20 bg-accent/10 rounded-lg flex items-center justify-center border border-accent/20">
                  <FileText className="w-8 h-8 text-accent" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-xs text-muted-foreground mb-1 font-medium uppercase tracking-wide">
                    Master&apos;s Thesis
                  </p>
                  <h3 className="font-semibold text-lg leading-tight mb-2">
                    Why OpenDraft Will Save the World
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    A tongue-in-cheek thesis demonstrating what 19 AI agents can do in 20 minutes
                  </p>
                </div>
              </div>
            </div>

            {/* Stats Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 divide-x divide-y sm:divide-y-0 divide-border">
              {stats.map((stat) => (
                <div key={stat.label} className="p-5 text-center">
                  <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-accent/10 mb-3">
                    <stat.icon className="w-5 h-5 text-accent" />
                  </div>
                  <p className="text-2xl font-semibold">{stat.value}</p>
                  <p className="text-xs text-muted-foreground">{stat.label}</p>
                </div>
              ))}
            </div>

            {/* Download Actions */}
            <div className="p-6 bg-muted/30 border-t border-border">
              <div className="flex flex-col sm:flex-row gap-3">
                <Button asChild size="lg" className="flex-1">
                  <Link
                    href="https://federicodeponte.github.io/opendraft/examples/Why_Academic_Thesis_AI_Saves_The_World.pdf"
                    target="_blank"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download PDF
                  </Link>
                </Button>
                <Button asChild variant="outline" size="lg" className="flex-1">
                  <Link
                    href="https://federicodeponte.github.io/opendraft/examples/academic_ai_thesis.docx"
                    target="_blank"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download Word
                  </Link>
                </Button>
                <Button asChild variant="outline" size="lg" className="flex-1">
                  <Link
                    href="https://federicodeponte.github.io/opendraft/examples/academic_ai_thesis.tex"
                    target="_blank"
                  >
                    <Code className="mr-2 h-4 w-4" />
                    View LaTeX
                  </Link>
                </Button>
              </div>
            </div>
          </div>

          {/* Trust note */}
          <p className="text-center text-xs text-muted-foreground mt-6">
            All citations verified via CrossRef & arXiv · Formatted in APA 7th Edition
          </p>
        </div>
      </div>
    </section>
  );
};
