import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Text,
} from '@react-email/components';
import * as React from 'react';
import { styles, colors, darkModeMediaQuery } from './styles';

interface PaymentConfirmationEmailProps {
  fullName: string;
  thesisTopic: string;
  paymentAmount: number;
  paymentCurrency: string;
}

export const PaymentConfirmationEmail = ({
  fullName = 'Student',
  thesisTopic = 'Your Thesis Topic',
  paymentAmount = 20.00,
  paymentCurrency = 'EUR',
}: PaymentConfirmationEmailProps) => (
  <Html>
    <Head>
      <style>{darkModeMediaQuery}</style>
    </Head>
    <Preview>Payment Confirmed - Your thesis is being generated! 🎓</Preview>
    <Body style={styles.main} className="email-body">
      <Container style={styles.container} className="email-container">
        {/* Header */}
        <div style={styles.header}>
          <Text style={styles.logo}>OpenDraft</Text>
        </div>

        {/* Hero Section */}
        <div style={styles.heroSection}>
          <span className="info-badge" style={styles.badge}>
            💳 Payment Confirmed!
          </span>
          <Heading style={styles.h1}>Payment Successful, {fullName}!</Heading>
          <Text style={styles.heroText} className="email-text-muted">
            Your payment of {paymentAmount} {paymentCurrency} has been confirmed. We're now generating your thesis immediately!
          </Text>
        </div>

        {/* Payment Confirmation Card */}
        <div className="info-card" style={styles.cardSuccess}>
          <Text style={styles.cardTitle}>Payment Details</Text>
          <Text style={styles.cardText}>
            <span style={styles.strong}>Amount:</span> {paymentAmount} {paymentCurrency}
          </Text>
          <Text style={styles.cardText}>
            <span style={styles.strong}>Thesis Topic:</span> {thesisTopic}
          </Text>
          <Text style={styles.cardText}>
            <span style={styles.strong}>Status:</span> ✅ Payment confirmed - Processing started
          </Text>
        </div>

        {/* What's Next */}
        <div style={{ margin: `${styles.text.margin} 0` }}>
          <Heading style={styles.h2}>What Happens Next?</Heading>
          <Text style={styles.text}>
            🚀 <span style={styles.strong}>Now:</span> Your thesis is being generated by our AI agents
          </Text>
          <Text style={styles.text}>
            ⏱️ <span style={styles.strong}>Processing time:</span> Usually takes 30-60 minutes
          </Text>
          <Text style={styles.text}>
            📧 <span style={styles.strong}>When complete:</span> You'll receive an email with download links for PDF & Word files
          </Text>
        </div>

        {/* Alert Box */}
        <div className="alert-card" style={styles.cardInfo}>
          <Text style={{ color: colors.infoDark, fontSize: styles.textSmall.fontSize, lineHeight: styles.textSmall.lineHeight, margin: '0', padding: '0' }}>
            <span style={styles.strong}>📧 Check your email</span> in about an hour for your completed thesis. 
            The email will contain secure download links that expire in 7 days.
          </Text>
        </div>

        {/* Academic Honesty Box */}
        <div className="info-card" style={styles.cardInfo}>
          <Text style={styles.cardTitleInfo}>
            <span style={styles.strong}>📚 Academic Honesty Reminder</span>
          </Text>
          <Text style={styles.cardTextInfo} className="email-text-muted">
            This AI-generated thesis is a <span style={styles.strong}>research aid</span>, not a substitute for your own work.
            Check your institution's AI usage policy before submission.
          </Text>
        </div>

        {/* Footer */}
        <div style={styles.footerWrapper}>
          <Text style={styles.footer} className="email-text-subtle">
            Thanks for your purchase!
            <br />
            OpenDraft Team
          </Text>
          <Text style={styles.copyright} className="email-text-subtle">
            © 2025 OpenDraft ·{' '}
            <a href="https://opendraft.xyz" style={styles.link}>
              opendraft.xyz
            </a>
          </Text>
        </div>
      </Container>
    </Body>
  </Html>
);

export default PaymentConfirmationEmail;

