/**
 * Mock data for agents
 */

import type { Agent, AgentRun } from '@/lib/types/agents'

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'bulk-agent',
    type: 'bulk',
    name: 'Bulk Agent',
    description: 'Process CSV data with AI-powered prompts. Enrich, transform, and generate content at scale.',
    status: 'idle',
    lastRunAt: '2024-01-15T10:30:00Z',
    nextRunAt: null,
    runsCount: 142,
    successRate: 98.5,
    averageExecutionTime: 45.2,
    currentJobId: null,
    inputSchema: {
      required: ['CSV file', 'Prompt'],
      optional: ['Context variables', 'Output columns'],
      description: 'Upload a CSV file and provide a prompt template with variables',
    },
    outputSchema: {
      fields: ['Generated content', 'Metadata'],
      description: 'Returns enriched CSV with AI-generated columns',
    },
    metadata: {},
  },
  {
    id: 'aeo-domination-agent',
    type: 'aeo-domination',
    name: 'AEO Domination Agent',
    description: 'Automatically generate and optimize Answer Engine Optimization (AEO) content to dominate search results for long-tail queries.',
    status: 'running',
    lastRunAt: '2024-01-15T14:20:00Z',
    nextRunAt: '2024-01-16T08:00:00Z',
    runsCount: 89,
    successRate: 95.2,
    averageExecutionTime: 120.5,
    currentJobId: 'job-aeo-2024-01-15-1420',
    inputSchema: {
      required: ['Target keywords', 'Content type', 'Tone'],
      optional: ['Competitor URLs', 'Content length', 'SEO guidelines'],
      description: 'Provide target keywords and content preferences. Agent generates optimized AEO content.',
    },
    outputSchema: {
      fields: ['Optimized content', 'SEO score', 'Keyword density', 'Competitor analysis'],
      description: 'Returns AEO-optimized content with SEO metrics and competitor insights',
    },
    metadata: {
      currentKeywords: 15,
      contentGenerated: 8,
      totalKeywords: 25,
    },
  },
  {
    id: 'lead-crawling-agent',
    type: 'lead-crawling',
    name: 'Lead Crawling Agent',
    description: 'Automatically discover and extract leads from websites, social media, and public databases. Enriches contact information and company data.',
    status: 'idle',
    lastRunAt: '2024-01-15T09:15:00Z',
    nextRunAt: '2024-01-16T06:00:00Z',
    runsCount: 234,
    successRate: 92.8,
    averageExecutionTime: 180.3,
    currentJobId: null,
    inputSchema: {
      required: ['Target websites/URLs', 'Lead criteria'],
      optional: ['Industry filters', 'Company size', 'Geographic location'],
      description: 'Provide target sources and criteria for lead discovery',
    },
    outputSchema: {
      fields: ['Contact name', 'Email', 'Company', 'Title', 'LinkedIn URL', 'Company data'],
      description: 'Returns structured lead data with enriched contact information',
    },
    metadata: {
      lastCrawlSources: 12,
      leadsFound: 342,
    },
  },
  {
    id: 'outbound-campaign-agent',
    type: 'outbound-campaign',
    name: 'Outbound Campaign Agent',
    description: 'Create and execute personalized outbound email campaigns. Generates personalized messages, sequences, and tracks engagement.',
    status: 'completed',
    lastRunAt: '2024-01-15T11:45:00Z',
    nextRunAt: '2024-01-16T09:00:00Z',
    runsCount: 67,
    successRate: 88.5,
    averageExecutionTime: 95.7,
    currentJobId: null,
    inputSchema: {
      required: ['Contact list', 'Campaign goal', 'Message template'],
      optional: ['Personalization variables', 'Send schedule', 'Follow-up rules'],
      description: 'Provide contact list and campaign configuration',
    },
    outputSchema: {
      fields: ['Sent emails', 'Open rate', 'Reply rate', 'Engagement metrics', 'Personalized content'],
      description: 'Returns campaign performance metrics and personalized message content',
    },
    metadata: {
      lastCampaignEmails: 150,
      openRate: 42.3,
      replyRate: 8.7,
    },
  },
  {
    id: 'gtm-analytics-agent',
    type: 'gtm-analytics',
    name: 'GTM Analytics Agent',
    description: 'Analyze go-to-market strategies, track performance metrics, and generate insights from sales and marketing data.',
    status: 'idle',
    lastRunAt: '2024-01-14T16:30:00Z',
    nextRunAt: '2024-01-16T10:00:00Z',
    runsCount: 45,
    successRate: 96.7,
    averageExecutionTime: 60.8,
    currentJobId: null,
    inputSchema: {
      required: ['Sales data', 'Marketing data', 'Time period'],
      optional: ['Channel filters', 'Product filters', 'Segment filters'],
      description: 'Provide sales and marketing data for analysis',
    },
    outputSchema: {
      fields: ['Performance metrics', 'Trends', 'Recommendations', 'ROI analysis', 'Channel performance'],
      description: 'Returns comprehensive GTM analytics with insights and recommendations',
    },
    metadata: {
      lastAnalysisPeriod: 'Q4 2023',
      metricsAnalyzed: 28,
    },
  },
  {
    id: 'market-analytics-agent',
    type: 'market-analytics',
    name: 'Market Analytics Agent',
    description: 'Analyze market trends, competitor landscapes, and industry insights. Generates market intelligence reports.',
    status: 'failed',
    lastRunAt: '2024-01-15T13:00:00Z',
    nextRunAt: '2024-01-16T12:00:00Z',
    runsCount: 32,
    successRate: 87.5,
    averageExecutionTime: 240.1,
    currentJobId: null,
    inputSchema: {
      required: ['Market/Industry', 'Analysis scope'],
      optional: ['Competitor list', 'Geographic region', 'Time frame'],
      description: 'Define market scope and analysis parameters',
    },
    outputSchema: {
      fields: ['Market size', 'Growth trends', 'Competitor analysis', 'Opportunities', 'Threats', 'Market share'],
      description: 'Returns comprehensive market analysis with trends and competitive intelligence',
    },
    metadata: {
      lastMarketAnalyzed: 'SaaS CRM',
      competitorsAnalyzed: 15,
      errorMessage: 'API rate limit exceeded',
    },
  },
]

export const MOCK_AGENT_RUNS: AgentRun[] = [
  {
    id: 'run-aeo-001',
    agentId: 'aeo-domination-agent',
    agentType: 'aeo-domination',
    status: 'running',
    startedAt: '2024-01-15T14:20:00Z',
    completedAt: null,
    recordsProcessed: 8,
    recordsTotal: 25,
    errorMessage: null,
    metadata: {},
  },
  {
    id: 'run-outbound-001',
    agentId: 'outbound-campaign-agent',
    agentType: 'outbound-campaign',
    status: 'completed',
    startedAt: '2024-01-15T11:45:00Z',
    completedAt: '2024-01-15T11:47:20Z',
    recordsProcessed: 150,
    recordsTotal: 150,
    errorMessage: null,
    metadata: {},
  },
  {
    id: 'run-market-001',
    agentId: 'market-analytics-agent',
    agentType: 'market-analytics',
    status: 'failed',
    startedAt: '2024-01-15T13:00:00Z',
    completedAt: '2024-01-15T13:04:15Z',
    recordsProcessed: 12,
    recordsTotal: 15,
    errorMessage: 'API rate limit exceeded',
    metadata: {},
  },
]

